package com.echoingvoid.registry;

import com.echoingvoid.EchoingVoid;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.Registries;
import net.minecraftforge.eventbus.api.bus.BusGroup;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

/**
 * The mod's particles. One so far.
 *
 * <p>PLAYER: "build a new particle effect, identical to the original one from the resonant
 * chestplate, but pink for the knell. the knell needs to feel special in every way."
 *
 * <p>{@code SimpleParticleType} because this carries no per-spawn data - the same reason vanilla's
 * own SONIC_BOOM is one. The sixteen frames live in
 * {@code assets/echoing_void/particles/knell_boom.json} and are generated by
 * {@code tools/gen_particle_textures.py} from measurements of vanilla's sequence.
 *
 * <p>{@code false} to the constructor is the overrideLimiter flag: like the sonic boom, this is a
 * one-shot effect a player deliberately triggered, but it is not important enough to force past a
 * client's particle-density setting.
 */
public final class ModParticles {
    private ModParticles() {}

    public static final DeferredRegister<ParticleType<?>> PARTICLES =
            DeferredRegister.create(Registries.PARTICLE_TYPE, EchoingVoid.MODID);

    /** The Knell release: vanilla's shock-front animation, in knell's own colours. */
    public static final RegistryObject<SimpleParticleType> KNELL_BOOM =
            PARTICLES.register("knell_boom", () -> new SimpleParticleType(false));

    public static void register(BusGroup modBus) {
        PARTICLES.register(modBus);
    }
}
