package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The chime mote: a null-iron cage around a lit core, four vanes and a tail wisp.
 *
 * <p>Nothing here reads the walk cycle. The mote has no gait and never touches the
 * ground, so every motion is driven by age alone: the cage turns slowly, the core
 * breathes inside it, the vanes fan a quarter cycle apart and the tail trails behind
 * on a slower period than everything else. The result is that a stationary mote is
 * still visibly alive, which is the entire reason the creature exists.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/chime_mote.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class ChimeMoteModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("chime_mote"), "main");

    /** The cage. Turns on its own axis. */
    private final ModelPart shell;
    /** The lit centre; it rises and falls inside the cage. */
    private final ModelPart core;
    /** The four vanes, one per quadrant. */
    private final ModelPart[] fins;
    /** Trailing wisp. Gives the lamp a down direction. */
    private final ModelPart tail;

    public ChimeMoteModel(ModelPart root) {
        super(root);
        this.shell = root.getChild("root").getChild("shell");
        this.core = root.getChild("root").getChild("shell").getChild("core");
        this.fins = new ModelPart[] {
                root.getChild("root").getChild("shell").getChild("fin_1"),
                root.getChild("root").getChild("shell").getChild("fin_2"),
                root.getChild("root").getChild("shell").getChild("fin_3"),
                root.getChild("root").getChild("shell").getChild("fin_4")
        };
        this.tail = root.getChild("root").getChild("shell").getChild("tail");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition shell = root.addOrReplaceChild(
                "shell",
                CubeListBuilder.create()
                        .texOffs(16, 0)
                        .addBox(-3.0F, -3.0F, -3.0F, 1.0F, 7.0F, 1.0F)
                        .texOffs(16, 0)
                        .addBox(2.0F, -3.0F, -3.0F, 1.0F, 7.0F, 1.0F)
                        .texOffs(16, 0)
                        .addBox(-3.0F, -3.0F, 2.0F, 1.0F, 7.0F, 1.0F)
                        .texOffs(16, 0)
                        .addBox(2.0F, -3.0F, 2.0F, 1.0F, 7.0F, 1.0F)
                        .texOffs(20, 0)
                        .addBox(-3.0F, -4.0F, -3.0F, 6.0F, 1.0F, 6.0F)
                        .texOffs(20, 0)
                        .addBox(-3.0F, 4.0F, -3.0F, 6.0F, 1.0F, 6.0F)
                        .texOffs(8, 9)
                        .addBox(-1.0F, -6.0F, -1.0F, 2.0F, 2.0F, 2.0F),
                PartPose.offset(0.0F, -8.0F, 0.0F));

        shell.addOrReplaceChild(
                "core",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-2.0F, -2.0F, -2.0F, 4.0F, 5.0F, 4.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        shell.addOrReplaceChild(
                "fin_1",
                CubeListBuilder.create()
                        .texOffs(44, 0)
                        .addBox(-2.0F, 4.0F, 3.0F, 4.0F, 1.0F, 4.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        shell.addOrReplaceChild(
                "fin_2",
                CubeListBuilder.create()
                        .texOffs(44, 0)
                        .addBox(-2.0F, 4.0F, 3.0F, 4.0F, 1.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 1.570796F, 0.0F));

        shell.addOrReplaceChild(
                "fin_3",
                CubeListBuilder.create()
                        .texOffs(44, 0)
                        .addBox(-2.0F, 4.0F, 3.0F, 4.0F, 1.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 3.141593F, 0.0F));

        shell.addOrReplaceChild(
                "fin_4",
                CubeListBuilder.create()
                        .texOffs(44, 0)
                        .addBox(-2.0F, 4.0F, 3.0F, 4.0F, 1.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 4.712389F, 0.0F));

        shell.addOrReplaceChild(
                "tail",
                CubeListBuilder.create()
                        .texOffs(0, 9)
                        .addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F),
                PartPose.offset(0.0F, 5.0F, 0.0F));

        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float age = state.ageInTicks;

        this.shell.yRot += age * 0.03F;
        this.core.y += Mth.sin(age * 0.14F) * 0.6F;
        this.tail.xRot += Mth.cos(age * 0.09F) * 0.18F;
        this.tail.zRot += Mth.sin(age * 0.07F) * 0.14F;

        for (int i = 0; i < this.fins.length; i++) {
            float phase = i * ((float) Math.PI / 2.0F);
            this.fins[i].xRot += Mth.cos(age * 0.18F + phase) * 0.35F;
            this.fins[i].y += Mth.sin(age * 0.18F + phase) * 0.4F;
        }
    }
}
