package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The drone auroch: a massive, stoic resonant bovine with sweeping tuning horns
 * and an acoustic dewlap that hums a low drone.
 *
 * <p>Walks with a heavy, steady quad gait. The massive head and horn assembly
 * sways gently with look direction and step cadence, while the throat resonator
 * breathes on a continuous slow idle.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/drone_auroch.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class DroneAurochModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("drone_auroch"), "main");

    /** Massive horned skull. Tracks pitch and yaw. */
    private final ModelPart head;
    /** Main torso chassis with dorsal plate and dewlap. */
    private final ModelPart body;
    /** Trailing chime tail. */
    private final ModelPart tail;
    /** Front left leg. */
    private final ModelPart legFl;
    /** Front right leg. */
    private final ModelPart legFr;
    /** Back left leg. */
    private final ModelPart legBl;
    /** Back right leg. */
    private final ModelPart legBr;

    public DroneAurochModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("body").getChild("head");
        this.body = root.getChild("root").getChild("body");
        this.tail = root.getChild("root").getChild("body").getChild("tail");
        this.legFl = root.getChild("root").getChild("body").getChild("leg_fl");
        this.legFr = root.getChild("root").getChild("body").getChild("leg_fr");
        this.legBl = root.getChild("root").getChild("body").getChild("leg_bl");
        this.legBr = root.getChild("root").getChild("body").getChild("leg_br");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition body = root.addOrReplaceChild(
                "body",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-7.0F, -6.0F, -10.0F, 14.0F, 12.0F, 20.0F)
                        .texOffs(0, 32)
                        .addBox(-5.0F, -10.0F, -8.0F, 10.0F, 4.0F, 10.0F)
                        .texOffs(40, 32)
                        .addBox(-3.0F, 1.0F, -10.0F, 6.0F, 6.0F, 8.0F),
                PartPose.offset(0.0F, -15.0F, 0.0F));

        PartDefinition head = body.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(68, 0)
                        .addBox(-4.5F, -5.0F, -7.0F, 9.0F, 9.0F, 8.0F)
                        .texOffs(68, 32)
                        .addBox(-3.5F, 0.0F, -11.0F, 7.0F, 5.0F, 5.0F)
                        .texOffs(0, 46)
                        .addBox(-4.0F, -6.0F, -6.0F, 8.0F, 2.0F, 6.0F),
                PartPose.offset(0.0F, -1.0F, -11.0F));

        PartDefinition horn_l_base = head.addOrReplaceChild(
                "horn_l_base",
                CubeListBuilder.create()
                        .texOffs(104, 32)
                        .addBox(-2.5F, -3.0F, -2.0F, 4.0F, 3.0F, 3.0F),
                PartPose.offset(-6.0F, -2.0F, -3.0F));

        horn_l_base.addOrReplaceChild(
                "horn_l_tip",
                CubeListBuilder.create()
                        .texOffs(92, 32)
                        .addBox(-1.5F, -6.0F, -3.0F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(-2.0F, -3.0F, -1.0F));

        head.addOrReplaceChild(
                "ear_l",
                CubeListBuilder.create()
                        .texOffs(118, 32)
                        .addBox(-3.0F, -1.0F, -1.0F, 4.0F, 2.0F, 1.0F),
                PartPose.offset(-5.0F, -1.0F, -2.0F));

        PartDefinition horn_r_base = head.addOrReplaceChild(
                "horn_r_base",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(104, 32)
                        .addBox(-1.5F, -3.0F, -2.0F, 4.0F, 3.0F, 3.0F),
                PartPose.offset(6.0F, -2.0F, -3.0F));

        horn_r_base.addOrReplaceChild(
                "horn_r_tip",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(92, 32)
                        .addBox(-1.5F, -6.0F, -3.0F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(2.0F, -3.0F, -1.0F));

        head.addOrReplaceChild(
                "ear_r",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(118, 32)
                        .addBox(-1.0F, -1.0F, -1.0F, 4.0F, 2.0F, 1.0F),
                PartPose.offset(5.0F, -1.0F, -2.0F));

        body.addOrReplaceChild(
                "leg_fl",
                CubeListBuilder.create()
                        .texOffs(102, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 10.0F, 4.0F),
                PartPose.offset(-4.5F, 5.0F, -6.0F));

        body.addOrReplaceChild(
                "leg_bl",
                CubeListBuilder.create()
                        .texOffs(102, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 10.0F, 4.0F),
                PartPose.offset(-4.5F, 5.0F, 6.0F));

        body.addOrReplaceChild(
                "leg_fr",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(102, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 10.0F, 4.0F),
                PartPose.offset(4.5F, 5.0F, -6.0F));

        body.addOrReplaceChild(
                "leg_br",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(102, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 10.0F, 4.0F),
                PartPose.offset(4.5F, 5.0F, 6.0F));

        body.addOrReplaceChild(
                "tail",
                CubeListBuilder.create()
                        .texOffs(118, 0)
                        .addBox(-1.0F, 0.0F, 0.0F, 2.0F, 10.0F, 2.0F)
                        .texOffs(28, 46)
                        .addBox(-1.5F, 10.0F, -0.5F, 3.0F, 3.0F, 3.0F),
                PartPose.offset(0.0F, -3.0F, 10.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.66F;
        float speed = Math.min(state.walkAnimationSpeed, 1.0F);
        float age = state.ageInTicks;

        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F);
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F);

        // Heavy quad gait: opposite diagonals in phase
        this.legFl.xRot += Mth.cos(pos) * 1.0F * speed;
        this.legFr.xRot += Mth.cos(pos + (float) Math.PI) * 1.0F * speed;
        this.legBl.xRot += Mth.cos(pos + (float) Math.PI) * 1.0F * speed;
        this.legBr.xRot += Mth.cos(pos) * 1.0F * speed;

        // Gentle body and tail sway
        this.body.zRot += Mth.cos(pos) * 0.05F * speed;
        this.tail.zRot += Mth.cos(age * 0.1F) * 0.15F + Mth.cos(pos) * 0.2F * speed;
    }
}
