package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The echo weaver: a ceiling-dwelling ambusher built around a segmented cephalothorax,
 * four acoustic crests and eight three-jointed legs.
 *
 * <p>The walk cycle is the vanilla spider's, extended to eight legs: legs a quarter cycle
 * apart in each rank, ranks half a cycle out of phase, so four feet are always planted.
 * The crests keep moving when the body is still, because listening is what the weaver
 * does between ambushes.
 *
 * <p>Head tracking is deliberately absent. The cephalothorax carries every leg, so turning
 * it to face the player would swing the whole animal off its feet.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/echo_weaver.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class EchoWeaverModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("echo_weaver"), "main");

    /** Hip segments, left rank first. Index order matches legTibias. */
    private final ModelPart[] legFemurs;
    /** Knee segments; they counter-flex against the femur's lift. */
    private final ModelPart[] legTibias;
    /** The four acoustic crests. */
    private final ModelPart[] crests;
    /** Rear segment. */
    private final ModelPart abdomen;

    public EchoWeaverModel(ModelPart root) {
        super(root);
        this.legFemurs = new ModelPart[] {
                root.getChild("root").getChild("cephalothorax").getChild("leg_l1_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l2_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l3_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l4_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r1_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r2_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r3_femur"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r4_femur")
        };
        this.legTibias = new ModelPart[] {
                root.getChild("root").getChild("cephalothorax").getChild("leg_l1_femur").getChild("leg_l1_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l2_femur").getChild("leg_l2_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l3_femur").getChild("leg_l3_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_l4_femur").getChild("leg_l4_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r1_femur").getChild("leg_r1_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r2_femur").getChild("leg_r2_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r3_femur").getChild("leg_r3_tibia"),
                root.getChild("root").getChild("cephalothorax").getChild("leg_r4_femur").getChild("leg_r4_tibia")
        };
        this.crests = new ModelPart[] {
                root.getChild("root").getChild("cephalothorax").getChild("crest_1"),
                root.getChild("root").getChild("cephalothorax").getChild("crest_2"),
                root.getChild("root").getChild("cephalothorax").getChild("crest_3"),
                root.getChild("root").getChild("cephalothorax").getChild("crest_4")
        };
        this.abdomen = root.getChild("root").getChild("cephalothorax").getChild("thorax_segment").getChild("abdomen");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition cephalothorax = root.addOrReplaceChild(
                "cephalothorax",
                CubeListBuilder.create()
                        .texOffs(0, 31)
                        .addBox(-7.0F, -5.0F, -10.0F, 14.0F, 11.0F, 16.0F)
                        .texOffs(0, 58)
                        .addBox(-5.0F, -2.0F, -17.0F, 10.0F, 8.0F, 7.0F)
                        .mirror()
                        .texOffs(114, 31)
                        .addBox(-4.0F, 5.0F, -17.0F, 3.0F, 5.0F, 4.0F)
                        .mirror(false)
                        .texOffs(114, 31)
                        .addBox(1.0F, 5.0F, -17.0F, 3.0F, 5.0F, 4.0F),
                PartPose.offset(0.0F, -16.0F, -4.0F));

        PartDefinition thorax_segment = cephalothorax.addOrReplaceChild(
                "thorax_segment",
                CubeListBuilder.create()
                        .texOffs(86, 0)
                        .addBox(-6.0F, -4.0F, -2.0F, 12.0F, 9.0F, 9.0F),
                PartPose.offset(0.0F, 0.0F, 8.0F));

        thorax_segment.addOrReplaceChild(
                "abdomen",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-9.0F, -5.0F, -2.0F, 18.0F, 14.0F, 17.0F)
                        .texOffs(60, 31)
                        .addBox(-7.0F, -7.0F, 0.0F, 14.0F, 3.0F, 13.0F)
                        .texOffs(34, 58)
                        .addBox(-3.0F, 3.0F, 15.0F, 6.0F, 5.0F, 4.0F),
                PartPose.offset(0.0F, 0.0F, 8.0F));

        cephalothorax.addOrReplaceChild(
                "crest_1",
                CubeListBuilder.create()
                        .texOffs(70, 0)
                        .addBox(-1.0F, -13.0F, -2.0F, 2.0F, 13.0F, 6.0F),
                PartPose.offsetAndRotation(-6.0F, -5.0F, 0.0F, -0.453786F, -0.418879F, 0.0F));

        cephalothorax.addOrReplaceChild(
                "crest_2",
                CubeListBuilder.create()
                        .texOffs(70, 0)
                        .addBox(-1.0F, -13.0F, -2.0F, 2.0F, 13.0F, 6.0F),
                PartPose.offsetAndRotation(-2.0F, -5.0F, 0.0F, -0.453786F, -0.15708F, 0.0F));

        cephalothorax.addOrReplaceChild(
                "crest_3",
                CubeListBuilder.create()
                        .texOffs(70, 0)
                        .addBox(-1.0F, -13.0F, -2.0F, 2.0F, 13.0F, 6.0F),
                PartPose.offsetAndRotation(2.0F, -5.0F, 0.0F, -0.453786F, 0.15708F, 0.0F));

        cephalothorax.addOrReplaceChild(
                "crest_4",
                CubeListBuilder.create()
                        .texOffs(70, 0)
                        .addBox(-1.0F, -13.0F, -2.0F, 2.0F, 13.0F, 6.0F),
                PartPose.offsetAndRotation(6.0F, -5.0F, 0.0F, -0.453786F, 0.418879F, 0.0F));

        PartDefinition leg_l1_femur = cephalothorax.addOrReplaceChild(
                "leg_l1_femur",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(54, 58)
                        .addBox(-14.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-8.0F, 0.0F, -6.0F, 0.0F, 0.0F, 0.872665F));

        PartDefinition leg_l1_tibia = leg_l1_femur.addOrReplaceChild(
                "leg_l1_tibia",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 73)
                        .addBox(-20.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-14.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        leg_l1_tibia.addOrReplaceChild(
                "leg_l1_tarsus",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(90, 58)
                        .addBox(-10.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-20.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.523599F));

        PartDefinition leg_l2_femur = cephalothorax.addOrReplaceChild(
                "leg_l2_femur",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(54, 58)
                        .addBox(-14.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-8.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.872665F));

        PartDefinition leg_l2_tibia = leg_l2_femur.addOrReplaceChild(
                "leg_l2_tibia",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 73)
                        .addBox(-20.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-14.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        leg_l2_tibia.addOrReplaceChild(
                "leg_l2_tarsus",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(90, 58)
                        .addBox(-10.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-20.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.523599F));

        PartDefinition leg_l3_femur = cephalothorax.addOrReplaceChild(
                "leg_l3_femur",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(54, 58)
                        .addBox(-14.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-8.0F, 0.0F, 8.0F, 0.0F, 0.0F, 0.872665F));

        PartDefinition leg_l3_tibia = leg_l3_femur.addOrReplaceChild(
                "leg_l3_tibia",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 73)
                        .addBox(-20.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-14.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        leg_l3_tibia.addOrReplaceChild(
                "leg_l3_tarsus",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(90, 58)
                        .addBox(-10.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-20.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.523599F));

        PartDefinition leg_l4_femur = cephalothorax.addOrReplaceChild(
                "leg_l4_femur",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(54, 58)
                        .addBox(-14.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-8.0F, 0.0F, 15.0F, 0.0F, 0.0F, 0.872665F));

        PartDefinition leg_l4_tibia = leg_l4_femur.addOrReplaceChild(
                "leg_l4_tibia",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 73)
                        .addBox(-20.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-14.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        leg_l4_tibia.addOrReplaceChild(
                "leg_l4_tarsus",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(90, 58)
                        .addBox(-10.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-20.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.523599F));

        PartDefinition leg_r1_femur = cephalothorax.addOrReplaceChild(
                "leg_r1_femur",
                CubeListBuilder.create()
                        .texOffs(54, 58)
                        .addBox(0.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(8.0F, 0.0F, -6.0F, 0.0F, 0.0F, -0.872665F));

        PartDefinition leg_r1_tibia = leg_r1_femur.addOrReplaceChild(
                "leg_r1_tibia",
                CubeListBuilder.create()
                        .texOffs(0, 73)
                        .addBox(0.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(14.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        leg_r1_tibia.addOrReplaceChild(
                "leg_r1_tarsus",
                CubeListBuilder.create()
                        .texOffs(90, 58)
                        .addBox(0.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(20.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.523599F));

        PartDefinition leg_r2_femur = cephalothorax.addOrReplaceChild(
                "leg_r2_femur",
                CubeListBuilder.create()
                        .texOffs(54, 58)
                        .addBox(0.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(8.0F, 0.0F, 1.0F, 0.0F, 0.0F, -0.872665F));

        PartDefinition leg_r2_tibia = leg_r2_femur.addOrReplaceChild(
                "leg_r2_tibia",
                CubeListBuilder.create()
                        .texOffs(0, 73)
                        .addBox(0.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(14.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        leg_r2_tibia.addOrReplaceChild(
                "leg_r2_tarsus",
                CubeListBuilder.create()
                        .texOffs(90, 58)
                        .addBox(0.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(20.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.523599F));

        PartDefinition leg_r3_femur = cephalothorax.addOrReplaceChild(
                "leg_r3_femur",
                CubeListBuilder.create()
                        .texOffs(54, 58)
                        .addBox(0.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(8.0F, 0.0F, 8.0F, 0.0F, 0.0F, -0.872665F));

        PartDefinition leg_r3_tibia = leg_r3_femur.addOrReplaceChild(
                "leg_r3_tibia",
                CubeListBuilder.create()
                        .texOffs(0, 73)
                        .addBox(0.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(14.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        leg_r3_tibia.addOrReplaceChild(
                "leg_r3_tarsus",
                CubeListBuilder.create()
                        .texOffs(90, 58)
                        .addBox(0.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(20.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.523599F));

        PartDefinition leg_r4_femur = cephalothorax.addOrReplaceChild(
                "leg_r4_femur",
                CubeListBuilder.create()
                        .texOffs(54, 58)
                        .addBox(0.0F, -2.0F, -2.0F, 14.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(8.0F, 0.0F, 15.0F, 0.0F, 0.0F, -0.872665F));

        PartDefinition leg_r4_tibia = leg_r4_femur.addOrReplaceChild(
                "leg_r4_tibia",
                CubeListBuilder.create()
                        .texOffs(0, 73)
                        .addBox(0.0F, -1.5F, -1.5F, 20.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(14.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        leg_r4_tibia.addOrReplaceChild(
                "leg_r4_tarsus",
                CubeListBuilder.create()
                        .texOffs(90, 58)
                        .addBox(0.0F, -1.0F, -1.0F, 10.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(20.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.523599F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.6662F;
        float speed = state.walkAnimationSpeed;

        for (int i = 0; i < this.legFemurs.length; i++) {
            boolean left = i < 4;
            float phase = (i % 4) * ((float) Math.PI / 2.0F) + (left ? 0.0F : (float) Math.PI);
            float side = left ? -1.0F : 1.0F;
            float swing = -(Mth.cos(pos * 2.0F + phase) * 0.4F) * speed;
            float lift = Math.abs(Mth.sin(pos + phase) * 0.4F) * speed;
            this.legFemurs[i].yRot += swing * side;
            this.legFemurs[i].zRot += lift * side;
            this.legTibias[i].zRot -= lift * 0.6F * side;
        }

        for (int i = 0; i < this.crests.length; i++) {
            this.crests[i].xRot += Mth.cos(state.ageInTicks * 0.12F + i * 0.7F) * 0.06F;
        }

        this.abdomen.xRot += Mth.cos(state.ageInTicks * 0.05F) * 0.03F;
    }
}
