package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Mth;

/**
 * The resonance wraith: a floating core wrapped in four bands of layered ribbon.
 *
 * <p>Nothing here is driven by the walk cycle, because the wraith has no gait - it drifts.
 * Each band carries a travelling wave outward from the core, with every segment lagging
 * the one inboard of it and swinging wider, so the silhouette reads as sound leaving the
 * body. Movement speed only widens the wave; it never starts it.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/resonance_wraith.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class ResonanceWraithModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("resonance_wraith"), "main");

    /** The body proper. Bobs on the spot. */
    private final ModelPart core;
    /** The flat ring around the core. */
    private final ModelPart halo;
    /** Band roots, one per quadrant. */
    private final ModelPart[] bands;
    /** First ribbon segment of each band. */
    private final ModelPart[] bandInner;
    /** Second ribbon segment of each band. */
    private final ModelPart[] bandMid;
    /** Outermost ribbon segment of each band. */
    private final ModelPart[] bandOuter;

    public ResonanceWraithModel(ModelPart root) {
        super(root, RenderTypes::entityTranslucent);
        this.core = root.getChild("root").getChild("core");
        this.halo = root.getChild("root").getChild("core").getChild("core_halo");
        this.bands = new ModelPart[] {
                root.getChild("root").getChild("core").getChild("ribbon_1"),
                root.getChild("root").getChild("core").getChild("ribbon_2"),
                root.getChild("root").getChild("core").getChild("ribbon_3"),
                root.getChild("root").getChild("core").getChild("ribbon_4")
        };
        this.bandInner = new ModelPart[] {
                root.getChild("root").getChild("core").getChild("ribbon_1").getChild("ribbon_1_inner"),
                root.getChild("root").getChild("core").getChild("ribbon_2").getChild("ribbon_2_inner"),
                root.getChild("root").getChild("core").getChild("ribbon_3").getChild("ribbon_3_inner"),
                root.getChild("root").getChild("core").getChild("ribbon_4").getChild("ribbon_4_inner")
        };
        this.bandMid = new ModelPart[] {
                root.getChild("root").getChild("core").getChild("ribbon_1").getChild("ribbon_1_inner").getChild("ribbon_1_mid"),
                root.getChild("root").getChild("core").getChild("ribbon_2").getChild("ribbon_2_inner").getChild("ribbon_2_mid"),
                root.getChild("root").getChild("core").getChild("ribbon_3").getChild("ribbon_3_inner").getChild("ribbon_3_mid"),
                root.getChild("root").getChild("core").getChild("ribbon_4").getChild("ribbon_4_inner").getChild("ribbon_4_mid")
        };
        this.bandOuter = new ModelPart[] {
                root.getChild("root").getChild("core").getChild("ribbon_1").getChild("ribbon_1_inner").getChild("ribbon_1_mid").getChild("ribbon_1_outer"),
                root.getChild("root").getChild("core").getChild("ribbon_2").getChild("ribbon_2_inner").getChild("ribbon_2_mid").getChild("ribbon_2_outer"),
                root.getChild("root").getChild("core").getChild("ribbon_3").getChild("ribbon_3_inner").getChild("ribbon_3_mid").getChild("ribbon_3_outer"),
                root.getChild("root").getChild("core").getChild("ribbon_4").getChild("ribbon_4_inner").getChild("ribbon_4_mid").getChild("ribbon_4_outer")
        };
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition core = root.addOrReplaceChild(
                "core",
                CubeListBuilder.create()
                        .texOffs(0, 30)
                        .addBox(-6.0F, -6.0F, -6.0F, 12.0F, 12.0F, 12.0F)
                        .texOffs(50, 54)
                        .addBox(-3.0F, -3.0F, -3.0F, 6.0F, 6.0F, 6.0F),
                PartPose.offset(0.0F, -18.0F, 0.0F));

        core.addOrReplaceChild(
                "core_halo",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-14.0F, -1.0F, -14.0F, 28.0F, 2.0F, 28.0F),
                PartPose.offset(0.0F, -6.0F, 0.0F));

        PartDefinition ribbon_1 = core.addOrReplaceChild(
                "ribbon_1",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition ribbon_1_inner = ribbon_1.addOrReplaceChild(
                "ribbon_1_inner",
                CubeListBuilder.create()
                        .texOffs(48, 30)
                        .addBox(-9.0F, -1.0F, 0.0F, 18.0F, 2.0F, 11.0F)
                        .texOffs(74, 54)
                        .addBox(-7.0F, -3.0F, 1.0F, 14.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 6.0F, -0.279253F, 0.0F, 0.0F));

        PartDefinition ribbon_1_mid = ribbon_1_inner.addOrReplaceChild(
                "ribbon_1_mid",
                CubeListBuilder.create()
                        .texOffs(0, 54)
                        .addBox(-7.0F, -1.0F, 0.0F, 14.0F, 2.0F, 11.0F)
                        .texOffs(0, 67)
                        .addBox(-5.0F, -3.0F, 1.0F, 10.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, 0.488692F, 0.0F, 0.0F));

        ribbon_1_mid.addOrReplaceChild(
                "ribbon_1_outer",
                CubeListBuilder.create()
                        .texOffs(38, 67)
                        .addBox(-5.0F, -1.0F, 0.0F, 10.0F, 2.0F, 6.0F)
                        .texOffs(106, 30)
                        .addBox(-3.0F, -3.0F, 1.0F, 6.0F, 1.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, -0.558505F, 0.0F, 0.0F));

        PartDefinition ribbon_2 = core.addOrReplaceChild(
                "ribbon_2",
                CubeListBuilder.create(),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 1.570796F, 0.0F));

        PartDefinition ribbon_2_inner = ribbon_2.addOrReplaceChild(
                "ribbon_2_inner",
                CubeListBuilder.create()
                        .texOffs(48, 30)
                        .addBox(-9.0F, -1.0F, 0.0F, 18.0F, 2.0F, 11.0F)
                        .texOffs(74, 54)
                        .addBox(-7.0F, -3.0F, 1.0F, 14.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 6.0F, -0.279253F, 0.0F, 0.0F));

        PartDefinition ribbon_2_mid = ribbon_2_inner.addOrReplaceChild(
                "ribbon_2_mid",
                CubeListBuilder.create()
                        .texOffs(0, 54)
                        .addBox(-7.0F, -1.0F, 0.0F, 14.0F, 2.0F, 11.0F)
                        .texOffs(0, 67)
                        .addBox(-5.0F, -3.0F, 1.0F, 10.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, 0.488692F, 0.0F, 0.0F));

        ribbon_2_mid.addOrReplaceChild(
                "ribbon_2_outer",
                CubeListBuilder.create()
                        .texOffs(38, 67)
                        .addBox(-5.0F, -1.0F, 0.0F, 10.0F, 2.0F, 6.0F)
                        .texOffs(106, 30)
                        .addBox(-3.0F, -3.0F, 1.0F, 6.0F, 1.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, -0.558505F, 0.0F, 0.0F));

        PartDefinition ribbon_3 = core.addOrReplaceChild(
                "ribbon_3",
                CubeListBuilder.create(),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 3.141593F, 0.0F));

        PartDefinition ribbon_3_inner = ribbon_3.addOrReplaceChild(
                "ribbon_3_inner",
                CubeListBuilder.create()
                        .texOffs(48, 30)
                        .addBox(-9.0F, -1.0F, 0.0F, 18.0F, 2.0F, 11.0F)
                        .texOffs(74, 54)
                        .addBox(-7.0F, -3.0F, 1.0F, 14.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 6.0F, -0.279253F, 0.0F, 0.0F));

        PartDefinition ribbon_3_mid = ribbon_3_inner.addOrReplaceChild(
                "ribbon_3_mid",
                CubeListBuilder.create()
                        .texOffs(0, 54)
                        .addBox(-7.0F, -1.0F, 0.0F, 14.0F, 2.0F, 11.0F)
                        .texOffs(0, 67)
                        .addBox(-5.0F, -3.0F, 1.0F, 10.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, 0.488692F, 0.0F, 0.0F));

        ribbon_3_mid.addOrReplaceChild(
                "ribbon_3_outer",
                CubeListBuilder.create()
                        .texOffs(38, 67)
                        .addBox(-5.0F, -1.0F, 0.0F, 10.0F, 2.0F, 6.0F)
                        .texOffs(106, 30)
                        .addBox(-3.0F, -3.0F, 1.0F, 6.0F, 1.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, -0.558505F, 0.0F, 0.0F));

        PartDefinition ribbon_4 = core.addOrReplaceChild(
                "ribbon_4",
                CubeListBuilder.create(),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 4.712389F, 0.0F));

        PartDefinition ribbon_4_inner = ribbon_4.addOrReplaceChild(
                "ribbon_4_inner",
                CubeListBuilder.create()
                        .texOffs(48, 30)
                        .addBox(-9.0F, -1.0F, 0.0F, 18.0F, 2.0F, 11.0F)
                        .texOffs(74, 54)
                        .addBox(-7.0F, -3.0F, 1.0F, 14.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 6.0F, -0.279253F, 0.0F, 0.0F));

        PartDefinition ribbon_4_mid = ribbon_4_inner.addOrReplaceChild(
                "ribbon_4_mid",
                CubeListBuilder.create()
                        .texOffs(0, 54)
                        .addBox(-7.0F, -1.0F, 0.0F, 14.0F, 2.0F, 11.0F)
                        .texOffs(0, 67)
                        .addBox(-5.0F, -3.0F, 1.0F, 10.0F, 1.0F, 9.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, 0.488692F, 0.0F, 0.0F));

        ribbon_4_mid.addOrReplaceChild(
                "ribbon_4_outer",
                CubeListBuilder.create()
                        .texOffs(38, 67)
                        .addBox(-5.0F, -1.0F, 0.0F, 10.0F, 2.0F, 6.0F)
                        .texOffs(106, 30)
                        .addBox(-3.0F, -3.0F, 1.0F, 6.0F, 1.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 1.0F, 11.0F, -0.558505F, 0.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float age = state.ageInTicks;
        float agitation = 1.0F + state.walkAnimationSpeed * 1.5F;

        this.core.y += Mth.sin(age * 0.08F) * 0.8F;
        this.halo.yRot += age * 0.02F;

        for (int i = 0; i < this.bands.length; i++) {
            float phase = i * ((float) Math.PI / 2.0F);
            this.bands[i].yRot += Mth.cos(age * 0.03F + phase) * 0.08F;
            this.bandInner[i].xRot += Mth.cos(age * 0.15F + phase) * 0.1F * agitation;
            this.bandMid[i].xRot += Mth.cos(age * 0.15F + phase - 0.9F) * 0.16F * agitation;
            this.bandOuter[i].xRot += Mth.cos(age * 0.15F + phase - 1.8F) * 0.22F * agitation;
        }
    }
}
