package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The strata golem: a slow, territorial quadruped with a low centre of mass and three
 * clusters of crystal spires on its back.
 *
 * <p>It rolls into a step rather than bobbing over it. The cadence is deliberately slower
 * than a vanilla quadruped's and the swing amplitude is capped, so a golem that has been
 * shoved does not windmill its legs. Diagonal pairs move together, which is what keeps a
 * heavy animal upright.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/strata_golem.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class StrataGolemModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("strata_golem"), "main");

    /** The whole body above the hips. */
    private final ModelPart chassis;
    /** Tracks the golem's look direction. */
    private final ModelPart head;
    /** Thighs, ordered left-front, left-back, right-front, right-back. */
    private final ModelPart[] legUppers;
    /** Feet, in the same order as legUppers. */
    private final ModelPart[] legLowers;
    /** Detachable crystal spire clusters. */
    private final ModelPart[] clusters;

    public StrataGolemModel(ModelPart root) {
        super(root);
        this.chassis = root.getChild("root").getChild("chassis");
        this.head = root.getChild("root").getChild("chassis").getChild("head");
        this.legUppers = new ModelPart[] {
                root.getChild("root").getChild("chassis").getChild("leg_l_front_upper"),
                root.getChild("root").getChild("chassis").getChild("leg_l_back_upper"),
                root.getChild("root").getChild("chassis").getChild("leg_r_front_upper"),
                root.getChild("root").getChild("chassis").getChild("leg_r_back_upper")
        };
        this.legLowers = new ModelPart[] {
                root.getChild("root").getChild("chassis").getChild("leg_l_front_upper").getChild("leg_l_front_lower"),
                root.getChild("root").getChild("chassis").getChild("leg_l_back_upper").getChild("leg_l_back_lower"),
                root.getChild("root").getChild("chassis").getChild("leg_r_front_upper").getChild("leg_r_front_lower"),
                root.getChild("root").getChild("chassis").getChild("leg_r_back_upper").getChild("leg_r_back_lower")
        };
        this.clusters = new ModelPart[] {
                root.getChild("root").getChild("chassis").getChild("chassis_plate").getChild("cluster_fore"),
                root.getChild("root").getChild("chassis").getChild("chassis_plate").getChild("cluster_mid"),
                root.getChild("root").getChild("chassis").getChild("chassis_plate").getChild("cluster_aft")
        };
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition chassis = root.addOrReplaceChild(
                "chassis",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-13.0F, -14.0F, -10.0F, 26.0F, 16.0F, 20.0F)
                        .texOffs(48, 87)
                        .addBox(-9.0F, 1.0F, -7.0F, 18.0F, 6.0F, 14.0F),
                PartPose.offset(0.0F, -24.0F, 0.0F));

        PartDefinition chassis_plate = chassis.addOrReplaceChild(
                "chassis_plate",
                CubeListBuilder.create()
                        .texOffs(0, 36)
                        .addBox(-15.0F, -6.0F, -8.0F, 30.0F, 6.0F, 20.0F)
                        .mirror()
                        .texOffs(92, 62)
                        .addBox(-19.0F, -6.0F, -5.0F, 4.0F, 9.0F, 14.0F)
                        .mirror(false)
                        .texOffs(92, 62)
                        .addBox(15.0F, -6.0F, -5.0F, 4.0F, 9.0F, 14.0F),
                PartPose.offset(0.0F, -14.0F, 0.0F));

        chassis.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(0, 62)
                        .addBox(-7.0F, 0.0F, -14.0F, 14.0F, 13.0F, 12.0F)
                        .texOffs(0, 108)
                        .addBox(-6.0F, 13.0F, -13.0F, 12.0F, 4.0F, 10.0F),
                PartPose.offset(0.0F, -12.0F, -10.0F));

        chassis_plate.addOrReplaceChild(
                "cluster_fore",
                CubeListBuilder.create()
                        .texOffs(92, 0)
                        .addBox(-5.0F, -20.0F, -2.0F, 5.0F, 20.0F, 5.0F)
                        .texOffs(112, 0)
                        .addBox(1.0F, -13.0F, 1.0F, 3.0F, 13.0F, 3.0F)
                        .texOffs(100, 36)
                        .addBox(-8.0F, -8.0F, 2.0F, 2.0F, 8.0F, 2.0F),
                PartPose.offset(0.0F, -6.0F, -6.0F));

        chassis_plate.addOrReplaceChild(
                "cluster_mid",
                CubeListBuilder.create()
                        .texOffs(92, 0)
                        .addBox(0.0F, -20.0F, -2.0F, 5.0F, 20.0F, 5.0F)
                        .texOffs(112, 0)
                        .addBox(-5.0F, -13.0F, 0.0F, 3.0F, 13.0F, 3.0F)
                        .texOffs(100, 36)
                        .addBox(6.0F, -8.0F, 1.0F, 2.0F, 8.0F, 2.0F),
                PartPose.offset(0.0F, -6.0F, 1.0F));

        chassis_plate.addOrReplaceChild(
                "cluster_aft",
                CubeListBuilder.create()
                        .texOffs(112, 0)
                        .addBox(-6.0F, -13.0F, -2.0F, 3.0F, 13.0F, 3.0F)
                        .texOffs(92, 0)
                        .addBox(0.0F, -20.0F, -1.0F, 5.0F, 20.0F, 5.0F)
                        .texOffs(100, 36)
                        .addBox(-2.0F, -8.0F, -4.0F, 2.0F, 8.0F, 2.0F),
                PartPose.offset(0.0F, -6.0F, 7.0F));

        PartDefinition leg_l_front_upper = chassis.addOrReplaceChild(
                "leg_l_front_upper",
                CubeListBuilder.create()
                        .texOffs(52, 62)
                        .addBox(-5.0F, 2.0F, -5.0F, 10.0F, 13.0F, 10.0F),
                PartPose.offset(-10.0F, 0.0F, -8.0F));

        leg_l_front_upper.addOrReplaceChild(
                "leg_l_front_lower",
                CubeListBuilder.create()
                        .texOffs(0, 87)
                        .addBox(-6.0F, 0.0F, -6.0F, 12.0F, 9.0F, 12.0F),
                PartPose.offset(0.0F, 15.0F, 0.0F));

        PartDefinition leg_l_back_upper = chassis.addOrReplaceChild(
                "leg_l_back_upper",
                CubeListBuilder.create()
                        .texOffs(52, 62)
                        .addBox(-5.0F, 2.0F, -5.0F, 10.0F, 13.0F, 10.0F),
                PartPose.offset(-10.0F, 0.0F, 8.0F));

        leg_l_back_upper.addOrReplaceChild(
                "leg_l_back_lower",
                CubeListBuilder.create()
                        .texOffs(0, 87)
                        .addBox(-6.0F, 0.0F, -6.0F, 12.0F, 9.0F, 12.0F),
                PartPose.offset(0.0F, 15.0F, 0.0F));

        PartDefinition leg_r_front_upper = chassis.addOrReplaceChild(
                "leg_r_front_upper",
                CubeListBuilder.create()
                        .texOffs(52, 62)
                        .addBox(-5.0F, 2.0F, -5.0F, 10.0F, 13.0F, 10.0F),
                PartPose.offset(10.0F, 0.0F, -8.0F));

        leg_r_front_upper.addOrReplaceChild(
                "leg_r_front_lower",
                CubeListBuilder.create()
                        .texOffs(0, 87)
                        .addBox(-6.0F, 0.0F, -6.0F, 12.0F, 9.0F, 12.0F),
                PartPose.offset(0.0F, 15.0F, 0.0F));

        PartDefinition leg_r_back_upper = chassis.addOrReplaceChild(
                "leg_r_back_upper",
                CubeListBuilder.create()
                        .texOffs(52, 62)
                        .addBox(-5.0F, 2.0F, -5.0F, 10.0F, 13.0F, 10.0F),
                PartPose.offset(10.0F, 0.0F, 8.0F));

        leg_r_back_upper.addOrReplaceChild(
                "leg_r_back_lower",
                CubeListBuilder.create()
                        .texOffs(0, 87)
                        .addBox(-6.0F, 0.0F, -6.0F, 12.0F, 9.0F, 12.0F),
                PartPose.offset(0.0F, 15.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.4F;
        // Cap the input: a golem knocked around should still move like a golem.
        float speed = Math.min(state.walkAnimationSpeed, 0.6F);

        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F);
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F);

        this.chassis.zRot += Mth.cos(pos) * 0.05F * speed;
        this.chassis.y += Mth.sin(pos * 2.0F) * 0.4F * speed;

        for (int i = 0; i < this.legUppers.length; i++) {
            // Left-front with right-back, left-back with right-front.
            float phase = (i == 0 || i == 3) ? 0.0F : (float) Math.PI;
            float swing = Mth.cos(pos + phase) * 0.6F * speed;
            this.legUppers[i].xRot += swing;
            // The foot only folds under on the recovery half of the stride.
            this.legLowers[i].xRot += Math.max(0.0F, -swing) * 0.5F;
        }

        for (int i = 0; i < this.clusters.length; i++) {
            float t = state.ageInTicks * 0.03F + i * 1.1F;
            this.clusters[i].zRot += Mth.cos(t) * 0.04F;
            this.clusters[i].xRot += Mth.sin(t * 0.7F) * 0.03F;
        }
    }
}
