package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The strata burrower: wedge head, paired mandibles, three body segments and six
 * stubby digging claws.
 *
 * <p>The body carries a yaw wave that starts at the snout and lags a fixed amount per
 * segment, so the animal swims through the ground rather than sliding over it. Only
 * the amplitude scales with movement speed; the wave itself is always running,
 * because a burrower that has stopped is still chewing.
 *
 * <p>The legs use the weaver's gait with the ranks re-phased for three pairs instead
 * of four, which keeps three feet planted at all times. The dorsal ridges move on
 * their own slow idle - they are what the player is meant to be watching for, so they
 * must never be perfectly still.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/strata_burrower.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class StrataBurrowerModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("strata_burrower"), "main");

    /** Wedge head. Tracks, but only partly - the neck is armour. */
    private final ModelPart head;
    /** The digging jaws. They chew on an idle of their own. */
    private final ModelPart[] mandibles;
    /** Body segments behind the shoulders, front to back. */
    private final ModelPart[] segments;
    /** The anchoring spur at the very back. */
    private final ModelPart tailSpur;
    /** Dorsal plates - the part visible above ground while it is burrowed. */
    private final ModelPart[] ridges;
    /** Hip segments, left rank first. Index order matches legClaws. */
    private final ModelPart[] legUppers;
    /** Digging claws; they counter-flex against the hip's lift. */
    private final ModelPart[] legClaws;

    public StrataBurrowerModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("body").getChild("head");
        this.mandibles = new ModelPart[] {
                root.getChild("root").getChild("body").getChild("head").getChild("mandible_l"),
                root.getChild("root").getChild("body").getChild("head").getChild("mandible_r")
        };
        this.segments = new ModelPart[] {
                root.getChild("root").getChild("body").getChild("segment_mid"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("segment_tail")
        };
        this.tailSpur = root.getChild("root").getChild("body").getChild("segment_mid").getChild("segment_tail").getChild("tail_spur");
        this.ridges = new ModelPart[] {
                root.getChild("root").getChild("body").getChild("ridge_fore"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("ridge_aft")
        };
        this.legUppers = new ModelPart[] {
                root.getChild("root").getChild("body").getChild("leg_l1_upper"),
                root.getChild("root").getChild("body").getChild("leg_l2_upper"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("leg_l3_upper"),
                root.getChild("root").getChild("body").getChild("leg_r1_upper"),
                root.getChild("root").getChild("body").getChild("leg_r2_upper"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("leg_r3_upper")
        };
        this.legClaws = new ModelPart[] {
                root.getChild("root").getChild("body").getChild("leg_l1_upper").getChild("leg_l1_claw"),
                root.getChild("root").getChild("body").getChild("leg_l2_upper").getChild("leg_l2_claw"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("leg_l3_upper").getChild("leg_l3_claw"),
                root.getChild("root").getChild("body").getChild("leg_r1_upper").getChild("leg_r1_claw"),
                root.getChild("root").getChild("body").getChild("leg_r2_upper").getChild("leg_r2_claw"),
                root.getChild("root").getChild("body").getChild("segment_mid").getChild("leg_r3_upper").getChild("leg_r3_claw")
        };
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition body = root.addOrReplaceChild(
                "body",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-9.0F, -6.0F, -6.0F, 18.0F, 13.0F, 12.0F),
                PartPose.offset(0.0F, -9.0F, -2.0F));

        PartDefinition head = body.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(60, 0)
                        .addBox(-8.0F, -5.0F, -13.0F, 16.0F, 11.0F, 13.0F)
                        .texOffs(0, 47)
                        .addBox(-6.0F, -7.0F, -11.0F, 12.0F, 3.0F, 10.0F),
                PartPose.offset(0.0F, 0.0F, -6.0F));

        head.addOrReplaceChild(
                "mandible_l",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(94, 25)
                        .addBox(-5.0F, -3.0F, -9.0F, 5.0F, 6.0F, 10.0F),
                PartPose.offsetAndRotation(-7.0F, 2.0F, -12.0F, 0.0F, 0.279253F, 0.0F));

        head.addOrReplaceChild(
                "mandible_r",
                CubeListBuilder.create()
                        .texOffs(94, 25)
                        .addBox(0.0F, -3.0F, -9.0F, 5.0F, 6.0F, 10.0F),
                PartPose.offsetAndRotation(7.0F, 2.0F, -12.0F, 0.0F, -0.279253F, 0.0F));

        body.addOrReplaceChild(
                "ridge_fore",
                CubeListBuilder.create()
                        .texOffs(44, 47)
                        .addBox(-3.0F, -4.0F, -3.0F, 6.0F, 4.0F, 8.0F),
                PartPose.offset(0.0F, -6.0F, -1.0F));

        PartDefinition segment_mid = body.addOrReplaceChild(
                "segment_mid",
                CubeListBuilder.create()
                        .texOffs(0, 25)
                        .addBox(-8.0F, -4.0F, 0.0F, 16.0F, 11.0F, 11.0F),
                PartPose.offset(0.0F, 0.0F, 6.0F));

        segment_mid.addOrReplaceChild(
                "ridge_aft",
                CubeListBuilder.create()
                        .texOffs(96, 47)
                        .addBox(-3.0F, -4.0F, -2.0F, 6.0F, 4.0F, 7.0F),
                PartPose.offset(0.0F, -4.0F, 4.0F));

        PartDefinition segment_tail = segment_mid.addOrReplaceChild(
                "segment_tail",
                CubeListBuilder.create()
                        .texOffs(54, 25)
                        .addBox(-6.0F, -3.0F, 0.0F, 12.0F, 9.0F, 8.0F),
                PartPose.offset(0.0F, 0.0F, 11.0F));

        segment_tail.addOrReplaceChild(
                "tail_spur",
                CubeListBuilder.create()
                        .texOffs(72, 47)
                        .addBox(-3.0F, -2.0F, 0.0F, 6.0F, 6.0F, 6.0F),
                PartPose.offset(0.0F, 1.0F, 8.0F));

        PartDefinition leg_l1_upper = body.addOrReplaceChild(
                "leg_l1_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 60)
                        .addBox(-7.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-9.0F, 3.0F, -2.0F, 0.0F, 0.0F, 0.436332F));

        leg_l1_upper.addOrReplaceChild(
                "leg_l1_claw",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(22, 60)
                        .addBox(-8.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-7.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        PartDefinition leg_l2_upper = body.addOrReplaceChild(
                "leg_l2_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 60)
                        .addBox(-7.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-9.0F, 3.0F, 3.0F, 0.0F, 0.0F, 0.436332F));

        leg_l2_upper.addOrReplaceChild(
                "leg_l2_claw",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(22, 60)
                        .addBox(-8.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-7.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        PartDefinition leg_l3_upper = segment_mid.addOrReplaceChild(
                "leg_l3_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 60)
                        .addBox(-7.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(-9.0F, 3.0F, 6.0F, 0.0F, 0.0F, 0.436332F));

        leg_l3_upper.addOrReplaceChild(
                "leg_l3_claw",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(22, 60)
                        .addBox(-8.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-7.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.832596F));

        PartDefinition leg_r1_upper = body.addOrReplaceChild(
                "leg_r1_upper",
                CubeListBuilder.create()
                        .texOffs(0, 60)
                        .addBox(0.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(9.0F, 3.0F, -2.0F, 0.0F, 0.0F, -0.436332F));

        leg_r1_upper.addOrReplaceChild(
                "leg_r1_claw",
                CubeListBuilder.create()
                        .texOffs(22, 60)
                        .addBox(0.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(7.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        PartDefinition leg_r2_upper = body.addOrReplaceChild(
                "leg_r2_upper",
                CubeListBuilder.create()
                        .texOffs(0, 60)
                        .addBox(0.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(9.0F, 3.0F, 3.0F, 0.0F, 0.0F, -0.436332F));

        leg_r2_upper.addOrReplaceChild(
                "leg_r2_claw",
                CubeListBuilder.create()
                        .texOffs(22, 60)
                        .addBox(0.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(7.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        PartDefinition leg_r3_upper = segment_mid.addOrReplaceChild(
                "leg_r3_upper",
                CubeListBuilder.create()
                        .texOffs(0, 60)
                        .addBox(0.0F, -2.0F, -2.0F, 7.0F, 4.0F, 4.0F),
                PartPose.offsetAndRotation(9.0F, 3.0F, 6.0F, 0.0F, 0.0F, -0.436332F));

        leg_r3_upper.addOrReplaceChild(
                "leg_r3_claw",
                CubeListBuilder.create()
                        .texOffs(22, 60)
                        .addBox(0.0F, -1.5F, -1.5F, 8.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(7.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.832596F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.7F;
        float speed = Math.min(state.walkAnimationSpeed, 0.9F);
        float age = state.ageInTicks;

        // A yaw wave from snout to tail, each segment lagging the one ahead of it.
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F) * 0.35F
                + Mth.cos(pos) * 0.12F * speed;
        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F) * 0.25F;
        this.segments[0].yRot += Mth.cos(pos - 0.8F) * 0.18F * speed;
        this.segments[1].yRot += Mth.cos(pos - 1.6F) * 0.26F * speed;
        this.tailSpur.yRot += Mth.cos(pos - 2.4F) * 0.32F * speed;

        for (int i = 0; i < this.mandibles.length; i++) {
            float side = i == 0 ? -1.0F : 1.0F;
            this.mandibles[i].yRot += side * (0.18F + Mth.cos(age * 0.25F) * 0.18F);
        }

        for (int i = 0; i < this.ridges.length; i++) {
            this.ridges[i].xRot += Mth.cos(age * 0.06F + i * 0.9F) * 0.05F;
        }

        for (int i = 0; i < this.legUppers.length; i++) {
            boolean left = i < 3;
            float phase = (i % 3) * ((float) Math.PI * 2.0F / 3.0F)
                    + (left ? 0.0F : (float) Math.PI);
            float side = left ? -1.0F : 1.0F;
            float swing = Mth.cos(pos * 2.0F + phase) * 0.5F * speed;
            float lift = Math.abs(Mth.sin(pos + phase)) * 0.35F * speed;
            this.legUppers[i].yRot += swing * side;
            this.legUppers[i].zRot += lift * side;
            this.legClaws[i].zRot -= lift * 0.7F * side;
        }
    }
}
