package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The thrum boar: a stout, armored rooter with forward-sweeping resonant tusks
 * and a vibrational dorsal comb that thrums with rhythmic acoustic energy.
 *
 * <p>Trots with a quick, rhythmic quad gait. The head bobs with a rooting rhythm
 * while the dorsal comb rapidly vibrates on a high-frequency idle.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/thrum_boar.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class ThrumBoarModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("thrum_boar"), "main");

    /** Wedge skull with tusks and snout. Tracks pitch and yaw. */
    private final ModelPart head;
    /** Barrel torso with dorsal vibrational comb. */
    private final ModelPart body;
    /** The dorsal vibrational comb spine. */
    private final ModelPart comb;
    /** Short bristly tail. */
    private final ModelPart tail;
    /** Front left leg. */
    private final ModelPart legFl;
    /** Front right leg. */
    private final ModelPart legFr;
    /** Back left leg. */
    private final ModelPart legBl;
    /** Back right leg. */
    private final ModelPart legBr;

    public ThrumBoarModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("body").getChild("head");
        this.body = root.getChild("root").getChild("body");
        this.comb = root.getChild("root").getChild("body").getChild("comb");
        this.tail = root.getChild("root").getChild("body").getChild("tail");
        this.legFl = root.getChild("root").getChild("body").getChild("leg_fl");
        this.legFr = root.getChild("root").getChild("body").getChild("leg_fr");
        this.legBl = root.getChild("root").getChild("body").getChild("leg_bl");
        this.legBr = root.getChild("root").getChild("body").getChild("leg_br");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition body = root.addOrReplaceChild(
                "body",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-5.0F, -5.0F, -7.0F, 10.0F, 9.0F, 15.0F)
                        .texOffs(0, 24)
                        .addBox(-5.5F, -4.0F, -3.0F, 1.0F, 6.0F, 8.0F)
                        .mirror()
                        .texOffs(0, 24)
                        .addBox(4.5F, -4.0F, -3.0F, 1.0F, 6.0F, 8.0F),
                PartPose.offset(0.0F, -8.0F, 0.0F));

        body.addOrReplaceChild(
                "comb",
                CubeListBuilder.create()
                        .texOffs(50, 0)
                        .addBox(-1.5F, -3.0F, -6.0F, 3.0F, 3.0F, 13.0F),
                PartPose.offset(0.0F, -5.0F, 0.0F));

        PartDefinition head = body.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(82, 0)
                        .addBox(-4.0F, -5.0F, -7.0F, 8.0F, 7.0F, 7.0F)
                        .texOffs(40, 24)
                        .addBox(-2.5F, -2.0F, -10.0F, 5.0F, 4.0F, 3.0F)
                        .texOffs(18, 24)
                        .addBox(-3.0F, -6.0F, -6.0F, 6.0F, 2.0F, 5.0F),
                PartPose.offset(0.0F, 1.0F, -7.0F));

        head.addOrReplaceChild(
                "tusk_l",
                CubeListBuilder.create()
                        .texOffs(56, 24)
                        .addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 3.0F),
                PartPose.offset(-3.5F, 2.0F, -8.0F));

        head.addOrReplaceChild(
                "ear_l",
                CubeListBuilder.create()
                        .texOffs(74, 24)
                        .addBox(-1.0F, -2.0F, -1.0F, 2.0F, 3.0F, 1.0F),
                PartPose.offset(-4.5F, -3.0F, -2.0F));

        head.addOrReplaceChild(
                "tusk_r",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(56, 24)
                        .addBox(-1.0F, -4.0F, -1.0F, 2.0F, 4.0F, 3.0F),
                PartPose.offset(3.5F, 2.0F, -8.0F));

        head.addOrReplaceChild(
                "ear_r",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(74, 24)
                        .addBox(-1.0F, -2.0F, -1.0F, 2.0F, 3.0F, 1.0F),
                PartPose.offset(4.5F, -3.0F, -2.0F));

        body.addOrReplaceChild(
                "leg_fl",
                CubeListBuilder.create()
                        .texOffs(112, 0)
                        .addBox(-1.5F, -1.0F, -1.5F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(-3.5F, 3.0F, -4.0F));

        body.addOrReplaceChild(
                "leg_bl",
                CubeListBuilder.create()
                        .texOffs(112, 0)
                        .addBox(-1.5F, -1.0F, -1.5F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(-3.5F, 3.0F, 5.0F));

        body.addOrReplaceChild(
                "leg_fr",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(112, 0)
                        .addBox(-1.5F, -1.0F, -1.5F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(3.5F, 3.0F, -4.0F));

        body.addOrReplaceChild(
                "leg_br",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(112, 0)
                        .addBox(-1.5F, -1.0F, -1.5F, 3.0F, 6.0F, 3.0F),
                PartPose.offset(3.5F, 3.0F, 5.0F));

        body.addOrReplaceChild(
                "tail",
                CubeListBuilder.create()
                        .texOffs(66, 24)
                        .addBox(-1.0F, -2.0F, 0.0F, 2.0F, 4.0F, 2.0F),
                PartPose.offset(0.0F, -2.0F, 8.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.8F;
        float speed = Math.min(state.walkAnimationSpeed, 1.0F);
        float age = state.ageInTicks;

        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F);
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F);

        // Quick rooting trot
        this.legFl.xRot += Mth.cos(pos) * 1.2F * speed;
        this.legFr.xRot += Mth.cos(pos + (float) Math.PI) * 1.2F * speed;
        this.legBl.xRot += Mth.cos(pos + (float) Math.PI) * 1.2F * speed;
        this.legBr.xRot += Mth.cos(pos) * 1.2F * speed;

        // Rooting bob and high-frequency thrum vibration
        this.head.xRot += Mth.sin(pos * 2.0F) * 0.1F * speed;
        this.comb.y += Mth.sin(age * 0.8F) * 0.3F;
        this.tail.zRot += Mth.cos(age * 0.2F) * 0.25F;
    }
}
