package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The tuner's protector: an iron-golem-shaped guardian built from oversized
 * plate limbs.
 *
 * <p>The walk is heavy and slightly delayed - each arm trails the opposite leg
 * rather than swinging with it, which is what makes something this wide read as
 * SLOW and DANGEROUS rather than comically stiff. The head barely moves; it is a
 * block of plate, not a face, and over-animating it undercuts the whole design.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/tuners_protector.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class TunersProtectorModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("tuners_protector"), "main");

    /** Minimal tracking - this is armour, not a face. */
    private final ModelPart head;
    /** Both legs, stepping together as a single heavy bone. */
    private final ModelPart legs;
    /** The oversized upper arms, left then right. */
    private final ModelPart[] armUppers;

    public TunersProtectorModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("legs").getChild("torso").getChild("head");
        this.legs = root.getChild("root").getChild("legs");
        this.armUppers = new ModelPart[] {
                root.getChild("root").getChild("legs").getChild("torso").getChild("arm_l_upper"),
                root.getChild("root").getChild("legs").getChild("torso").getChild("arm_r_upper")
        };
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition legs = root.addOrReplaceChild(
                "legs",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(84, 0)
                        .addBox(-8.0F, 0.0F, -4.0F, 6.0F, 12.0F, 8.0F)
                        .mirror(false)
                        .texOffs(84, 0)
                        .addBox(2.0F, 0.0F, -4.0F, 6.0F, 12.0F, 8.0F),
                PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition torso = legs.addOrReplaceChild(
                "torso",
                CubeListBuilder.create()
                        .texOffs(58, 23)
                        .addBox(-6.0F, -5.0F, -3.0F, 12.0F, 5.0F, 6.0F)
                        .texOffs(28, 0)
                        .addBox(-9.0F, -16.0F, -5.0F, 18.0F, 11.0F, 10.0F)
                        .texOffs(0, 40)
                        .addBox(-5.0F, -17.0F, -4.0F, 10.0F, 2.0F, 8.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        torso.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(26, 23)
                        .addBox(-4.0F, -8.0F, -5.0F, 8.0F, 8.0F, 8.0F),
                PartPose.offset(0.0F, -16.0F, 0.0F));

        PartDefinition arm_l_upper = torso.addOrReplaceChild(
                "arm_l_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 23)
                        .addBox(-3.0F, -1.0F, -3.5F, 6.0F, 10.0F, 7.0F),
                PartPose.offset(-12.0F, -14.0F, 0.0F));

        arm_l_upper.addOrReplaceChild(
                "arm_l_lower",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 0)
                        .addBox(-3.0F, 0.0F, -4.0F, 6.0F, 15.0F, 8.0F),
                PartPose.offset(0.0F, 9.0F, 0.0F));

        PartDefinition arm_r_upper = torso.addOrReplaceChild(
                "arm_r_upper",
                CubeListBuilder.create()
                        .texOffs(0, 23)
                        .addBox(-3.0F, -1.0F, -3.5F, 6.0F, 10.0F, 7.0F),
                PartPose.offset(12.0F, -14.0F, 0.0F));

        arm_r_upper.addOrReplaceChild(
                "arm_r_lower",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-3.0F, 0.0F, -4.0F, 6.0F, 15.0F, 8.0F),
                PartPose.offset(0.0F, 9.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.7F;
        float speed = Math.min(state.walkAnimationSpeed, 0.8F);

        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F) * 0.15F;
        this.legs.xRot += Mth.cos(pos) * 0.10F * speed;

        for (int i = 0; i < this.armUppers.length; i++) {
            float phase = i == 0 ? (float) Math.PI : 0.0F;
            this.armUppers[i].xRot -= Mth.cos(pos + phase) * 0.25F * speed;
        }
    }
}
