package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The tuner shade: a hooded robed caster carrying a spinning resonator ring.
 *
 * <p>The head tracks, because the shade is the one creature in the dimension that
 * looks at you rather than at where you are going. Below the waist there is only
 * robe: it leads the walk cycle by half a beat and swings on a longer period than
 * the shoulders, which is what makes cloth read as cloth on a rig with no legs.
 *
 * <p>The ring never stops turning, at a rate unrelated to anything else on the model.
 * It is the creature's tell - a shade with its ring up is about to fire - so it has to
 * be legible at the distance the bolt is fired from.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/tuner_shade.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class TunerShadeModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("tuner_shade"), "main");

    /** Hood. Tracks the look direction. */
    private final ModelPart head;
    /** Upper body above the waist. */
    private final ModelPart torso;
    /** The skirt and hem; there are no legs under it. */
    private final ModelPart robe;
    /** Shoulder mantle. Breathes on a slow idle. */
    private final ModelPart mantle;
    /** Upper arms, left then right. */
    private final ModelPart[] armUppers;
    /** Forearms, in the same order as armUppers. */
    private final ModelPart[] armLowers;
    /** The resonator. Spins constantly. */
    private final ModelPart ring;
    /** The mote held inside the ring. */
    private final ModelPart spark;

    public TunerShadeModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("robe").getChild("torso").getChild("head");
        this.torso = root.getChild("root").getChild("robe").getChild("torso");
        this.robe = root.getChild("root").getChild("robe");
        this.mantle = root.getChild("root").getChild("robe").getChild("torso").getChild("mantle");
        this.armUppers = new ModelPart[] {
                root.getChild("root").getChild("robe").getChild("torso").getChild("arm_l_upper"),
                root.getChild("root").getChild("robe").getChild("torso").getChild("arm_r_upper")
        };
        this.armLowers = new ModelPart[] {
                root.getChild("root").getChild("robe").getChild("torso").getChild("arm_l_upper").getChild("arm_l_lower"),
                root.getChild("root").getChild("robe").getChild("torso").getChild("arm_r_upper").getChild("arm_r_lower")
        };
        this.ring = root.getChild("root").getChild("robe").getChild("torso").getChild("ring");
        this.spark = root.getChild("root").getChild("robe").getChild("torso").getChild("ring").getChild("spark");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition robe = root.addOrReplaceChild(
                "robe",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-6.0F, 6.0F, -4.0F, 12.0F, 7.0F, 8.0F)
                        .texOffs(0, 15)
                        .addBox(-5.0F, 0.0F, -3.0F, 10.0F, 6.0F, 6.0F),
                PartPose.offset(0.0F, -13.0F, 0.0F));

        PartDefinition torso = robe.addOrReplaceChild(
                "torso",
                CubeListBuilder.create()
                        .texOffs(72, 0)
                        .addBox(-5.0F, -9.0F, -3.0F, 10.0F, 9.0F, 6.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        torso.addOrReplaceChild(
                "mantle",
                CubeListBuilder.create()
                        .texOffs(32, 15)
                        .addBox(-7.0F, 0.0F, -4.0F, 14.0F, 3.0F, 8.0F),
                PartPose.offset(0.0F, -9.0F, 0.0F));

        PartDefinition head = torso.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(40, 0)
                        .addBox(-4.0F, -7.0F, -4.0F, 8.0F, 7.0F, 8.0F),
                PartPose.offset(0.0F, -9.0F, 0.0F));

        head.addOrReplaceChild(
                "peak",
                CubeListBuilder.create()
                        .texOffs(76, 15)
                        .addBox(-2.0F, -2.0F, -2.0F, 4.0F, 3.0F, 4.0F),
                PartPose.offset(0.0F, -7.0F, 0.0F));

        PartDefinition arm_l_upper = torso.addOrReplaceChild(
                "arm_l_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(104, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offsetAndRotation(-6.0F, -8.0F, 0.0F, 0.0F, 0.0F, -0.087266F));

        arm_l_upper.addOrReplaceChild(
                "arm_l_lower",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(104, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.244346F, 0.0F, 0.0F));

        PartDefinition arm_r_upper = torso.addOrReplaceChild(
                "arm_r_upper",
                CubeListBuilder.create()
                        .texOffs(104, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offsetAndRotation(6.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.087266F));

        arm_r_upper.addOrReplaceChild(
                "arm_r_lower",
                CubeListBuilder.create()
                        .texOffs(104, 0)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.733038F, 0.0F, 0.0F));

        PartDefinition ring = torso.addOrReplaceChild(
                "ring",
                CubeListBuilder.create()
                        .texOffs(100, 15)
                        .addBox(-5.0F, -4.0F, -1.0F, 10.0F, 1.0F, 2.0F)
                        .texOffs(100, 15)
                        .addBox(-5.0F, 2.0F, -1.0F, 10.0F, 1.0F, 2.0F)
                        .mirror()
                        .texOffs(120, 0)
                        .addBox(-5.0F, -3.0F, -1.0F, 1.0F, 5.0F, 2.0F)
                        .mirror(false)
                        .texOffs(120, 0)
                        .addBox(4.0F, -3.0F, -1.0F, 1.0F, 5.0F, 2.0F),
                PartPose.offset(0.0F, 0.0F, -7.0F));

        ring.addOrReplaceChild(
                "spark",
                CubeListBuilder.create()
                        .texOffs(92, 15)
                        .addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos * 0.6F;
        float speed = Math.min(state.walkAnimationSpeed, 0.8F);
        float age = state.ageInTicks;

        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F);
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F);

        // The robe leads the shoulders and swings wider, so it reads as cloth.
        this.robe.yRot += Mth.cos(pos * 0.5F) * 0.10F * speed;
        this.robe.xRot += Mth.cos(pos) * 0.06F * speed;
        this.mantle.zRot += Mth.cos(age * 0.05F) * 0.03F;
        this.torso.xRot += Mth.cos(pos) * 0.04F * speed;

        for (int i = 0; i < this.armUppers.length; i++) {
            float side = i == 0 ? -1.0F : 1.0F;
            float phase = i == 0 ? 0.0F : (float) Math.PI;
            this.armUppers[i].xRot += Mth.cos(pos + phase) * 0.5F * speed;
            this.armUppers[i].zRot += side * (0.05F + Mth.cos(age * 0.07F) * 0.03F);
            this.armLowers[i].xRot -= Math.abs(Mth.sin(pos + phase)) * 0.3F * speed;
        }

        this.ring.zRot += age * 0.09F;
        this.ring.y += Mth.sin(age * 0.11F) * 0.5F;
        this.spark.yRot += age * 0.22F;
    }
}
