package com.echoingvoid.client.model;

import com.echoingvoid.EchoingVoid;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.util.Mth;

/**
 * The tuner trader: a robed, hatted figure with a satchel of goods.
 *
 * <p>A plain walk cycle - the whole point of the silhouette is that it reads as
 * an ordinary person, so the gait has to look ordinary too, unlike every other
 * creature down here which is deliberately built not to walk like one.
 *
 * <p>The geometry in this class is generated by {@code tools/gen_entity_models.py}
 * from {@code assets/echoing_void/geo/tuner_trader.geo.json}. Edit the geometry, then re-run
 * the generator; hand edits to {@code createBodyLayer} will be overwritten.
 */
public class TunerTraderModel extends EntityModel<LivingEntityRenderState> {
    /**
     * Where the baked mesh is filed. Registered against {@link #createBodyLayer()} in
     * {@code EchoingVoidClient} and looked up again by the renderer.
     */
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EchoingVoid.id("tuner_trader"), "main");

    /** Tracks the look direction. */
    private final ModelPart head;
    /** Both legs swing together as one bone - a robe hem, not a stride. */
    private final ModelPart legs;
    /** Sways a beat behind the torso. */
    private final ModelPart satchel;
    /** Upper arms, left then right. */
    private final ModelPart[] armUppers;

    public TunerTraderModel(ModelPart root) {
        super(root);
        this.head = root.getChild("root").getChild("legs").getChild("torso").getChild("head");
        this.legs = root.getChild("root").getChild("legs");
        this.satchel = root.getChild("root").getChild("legs").getChild("torso").getChild("satchel");
        this.armUppers = new ModelPart[] {
                root.getChild("root").getChild("legs").getChild("torso").getChild("arm_l_upper"),
                root.getChild("root").getChild("legs").getChild("torso").getChild("arm_r_upper")
        };
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition parts = mesh.getRoot();

        PartDefinition root = parts.addOrReplaceChild(
                "root",
                CubeListBuilder.create(),
                PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition legs = root.addOrReplaceChild(
                "legs",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 18)
                        .addBox(-4.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F)
                        .mirror(false)
                        .texOffs(0, 18)
                        .addBox(0.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F),
                PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition torso = legs.addOrReplaceChild(
                "torso",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(-4.0F, -12.0F, -3.0F, 8.0F, 12.0F, 6.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        torso.addOrReplaceChild(
                "satchel",
                CubeListBuilder.create()
                        .texOffs(0, 34)
                        .addBox(-1.0F, -2.0F, -3.0F, 3.0F, 6.0F, 6.0F),
                PartPose.offsetAndRotation(5.0F, -5.0F, 0.0F, 0.0F, 0.0F, 0.139626F));

        torso.addOrReplaceChild(
                "strap",
                CubeListBuilder.create()
                        .texOffs(16, 46)
                        .addBox(-4.0F, 2.0F, -1.0F, 8.0F, 2.0F, 2.0F),
                PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition head = torso.addOrReplaceChild(
                "head",
                CubeListBuilder.create()
                        .texOffs(28, 0)
                        .addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F),
                PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition brim = head.addOrReplaceChild(
                "brim",
                CubeListBuilder.create()
                        .texOffs(16, 18)
                        .addBox(-6.0F, 0.0F, -6.0F, 12.0F, 1.0F, 12.0F),
                PartPose.offset(0.0F, -8.0F, 0.0F));

        brim.addOrReplaceChild(
                "crown",
                CubeListBuilder.create()
                        .texOffs(34, 34)
                        .addBox(-3.0F, -3.0F, -3.0F, 6.0F, 3.0F, 6.0F),
                PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition arm_l_upper = torso.addOrReplaceChild(
                "arm_l_upper",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(18, 34)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offset(-6.0F, -11.0F, 0.0F));

        arm_l_upper.addOrReplaceChild(
                "arm_l_lower",
                CubeListBuilder.create()
                        .mirror()
                        .texOffs(0, 46)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 5.0F, 4.0F),
                PartPose.offset(0.0F, 6.0F, 0.0F));

        PartDefinition arm_r_upper = torso.addOrReplaceChild(
                "arm_r_upper",
                CubeListBuilder.create()
                        .texOffs(18, 34)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 6.0F, 4.0F),
                PartPose.offset(6.0F, -11.0F, 0.0F));

        arm_r_upper.addOrReplaceChild(
                "arm_r_lower",
                CubeListBuilder.create()
                        .texOffs(0, 46)
                        .addBox(-2.0F, 0.0F, -2.0F, 4.0F, 5.0F, 4.0F),
                PartPose.offset(0.0F, 6.0F, 0.0F));

        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        float pos = state.walkAnimationPos;
        float speed = Math.min(state.walkAnimationSpeed, 1.0F);
        float age = state.ageInTicks;

        this.head.xRot += state.xRot * ((float) Math.PI / 180.0F);
        this.head.yRot += state.yRot * ((float) Math.PI / 180.0F);

        this.legs.xRot += Mth.cos(pos) * 0.15F * speed;
        this.satchel.zRot += Mth.cos(age * 0.08F) * 0.06F;

        for (int i = 0; i < this.armUppers.length; i++) {
            float side = i == 0 ? -1.0F : 1.0F;
            this.armUppers[i].xRot += Mth.cos(pos + (i == 0 ? 0.0F : (float) Math.PI)) * 0.3F * speed;
        }
    }
}
